name: Generate all files

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate files independently using LaTeX docker
      uses: xu-cheng/latex-action@3.2.0
      with:
        root_file: |
          industry/resume.tex
          academic/academic_cv.tex
          cover_letter/letter.tex
        work_in_root_file_dir: true

    - name: Generate files using Makefile
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: make
