name: Generate all files using Makefile

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@3.2.0

    - name: Generate all files
      run: make
